name: flakka_protobuf_build_types
description: Compiled Dart type for flakka_protobuf_build
repository: https://github.com/flakka-code/flakka_protobuf_build_types
version: 0.4.0-alpha.1

environment:
  sdk: "^3.3.0"

dependencies:
  fixnum: ^1.1.0
  protobuf: ^3.1.0

dev_dependencies:
  build:
  build_runner:
  build_verify: ^3.1.0
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
