name: flakka_protobuf_build_types
description: Compiled Dart type for flakka_protobuf_build
version: 0.2.0

environment:
  sdk: "^3.3.0"

dependencies:
  fixnum:
  protobuf:

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
